on:
  push:
  pull_request:
 
jobs:
  build:
    runs-on: nomad
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: go build

