on:
  push:
  pull_request:
 
jobs:
  build-binary:
    runs-on: nomad
    strategy:
      matrix:
        arch: [amd64, arm64]
        os: [freebsd, darwin, linux]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: go build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
      - uses: actions/upload-artifact@v3
        with:
          name: nomad-follower-${{ matrix.os }}-${{ matrix.arch }}
          path: nomad-follower
