on:
  push:
  pull_request:
 
jobs:
  build:
    runs-on: nomad
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: go build
      - uses: actions/upload-artifact@v3
        with:
          name: nomad-follower
          path: nomad-follower

